// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4QsfqbOM33A9YpvTQJNdwStuZD9PB5T4',
    appId: '1:1025446756903:web:1598ca12a980f661d44402',
    messagingSenderId: '1025446756903',
    projectId: 'todo-cb0a2',
    authDomain: 'todo-cb0a2.firebaseapp.com',
    storageBucket: 'todo-cb0a2.appspot.com',
    measurementId: 'G-9M3J4CZ95L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1gzKTa3dEA1TbnY3-7EINdS-slMdRlm4',
    appId: '1:1025446756903:android:9c4d2a5945357f16d44402',
    messagingSenderId: '1025446756903',
    projectId: 'todo-cb0a2',
    storageBucket: 'todo-cb0a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTQQs2CGDclLNlpWfu2YYp4JePlrPLwPo',
    appId: '1:1025446756903:ios:5cb843e0f25ca951d44402',
    messagingSenderId: '1025446756903',
    projectId: 'todo-cb0a2',
    storageBucket: 'todo-cb0a2.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTQQs2CGDclLNlpWfu2YYp4JePlrPLwPo',
    appId: '1:1025446756903:ios:dbda14e6a0a688aed44402',
    messagingSenderId: '1025446756903',
    projectId: 'todo-cb0a2',
    storageBucket: 'todo-cb0a2.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
